### ISSUE TITLE
Error message "NameError: name 'asin' is not defined"

### ISSUE THREAD

**Issue by kpark53** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#13]
Hello, 

  I tried to run the code and I encountered a error message when I do the command prompt(python3 scripts/data_creation/filter_from_already_existing.py --data_path data/raw_datasets/10000 --csv_path test_set/nc.csv) to remove test and numerical problematic equatioins form the training dataset.

 I tried to add import asin along with lambdify but it didn't help. Could you pleaes advise?
 
 My environment is 
   Linux Ubuntu, Anaconda with python 3.8
  
  

```
Loading metadata
Creating image for validation set
Traceback (most recent call last):
  File "scripts/data_creation/filter_from_already_existing.py", line 131, in <module>
    main()
  File "/home/keun/anaconda3/envs/math_prob/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/keun/anaconda3/envs/math_prob/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/keun/anaconda3/envs/math_prob/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/keun/anaconda3/envs/math_prob/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/data_creation/filter_from_already_existing.py", line 113, in main
    target_image = evaluate_validation_set(validation,support)
  File "scripts/data_creation/filter_from_already_existing.py", line 29, in evaluate_validation_set
    curr = lambdify(variables,row["eq"])(*support).numpy().astype('float16')
  File "<lambdifygenerated-101>", line 2, in _lambdifygenerated
NameError: name 'asin' is not defined
```

**Comment by TommasoBendinelli** [comment]
See this related issue: https://github.com/SymposiumOrganization/NeuralSymbolicRegressionThatScales/issues/9

**Comment by kpark53** [comment]
Thanks Tommaso. Env list on `https://github.com/SymposiumOrganization/NeuralSymbolicRegressionThatScales/issues/9` was really helpful.
