### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = '/home/kpark53/code/NSR/data/validation/metadata.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by kpark53** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#14]
Hi Tommaso,
 
  I cleared out all the env dependency related, data-generation related errors but I encountered an error below when I was running the train script. 

As you can see, it's saying I don't have the metadat.h5 for validation. I followed the instruction on data-generation process but it didn't generate data/validation. Could you please advise?
 

 

```
/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/omegaconf/omegaconf.py:572: UserWarning: update() merge flag is is not specified, defaulting to False.
For more details, see https://github.com/omry/omegaconf/issues/367
  warnings.warn(
Global seed set to 9
wandb: Currently logged in as: nsr (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.15.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.22
wandb: Syncing run sparkling-firebrand-3
wandb: ⭐️ View project at https://wandb.ai/nsr/ICML
wandb: 🚀 View run at https://wandb.ai/nsr/ICML/runs/3s2wkb14
wandb: Run data is saved locally in /home/kpark53/code/NSR/run/True/2023-05-25/14-11-28/wandb/run-20230525_141128-3s2wkb14
wandb: Run `wandb offline` to turn off syncing.
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
Multi-processing is handled by Slurm.
Using native 16bit precision.
Traceback (most recent call last):
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/_internal/utils.py", line 207, in run_and_report
    return func()
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/_internal/utils.py", line 356, in <lambda>
    lambda: hydra.run(
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "scripts/train.py", line 59, in main
    trainer.fit(model, data)
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 457, in fit
    self.call_setup_hook(model)
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1062, in call_setup_hook
    self.datamodule.setup(stage_name)
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 92, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/kpark53/code/NSR/src/nesymres/architectures/data.py", line 265, in setup
    self.validation_dataset = NesymresDataset(
  File "/home/kpark53/code/NSR/src/nesymres/architectures/data.py", line 54, in __init__
    metadata = load_metadata_hdf5(hydra.utils.to_absolute_path(data_path))
  File "/home/kpark53/code/NSR/src/nesymres/utils.py", line 69, in load_metadata_hdf5
    f = h5py.File(os.path.join(path_folder,"metadata.h5"), 'r')
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/kpark53/code/NSR/data/validation/metadata.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/train.py", line 64, in <module>
    main()
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in _run_hydra
    run_and_report(
  File "/home/kpark53/.conda/envs/math/lib/python3.8/site-packages/hydra/_internal/utils.py", line 246, in run_and_report
    assert mdl is not None
AssertionError
wandb: Waiting for W&B process to finish, PID 1530054
wandb: Program failed with code 1.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)
wandb: \ 0.01MB of 0.01MB uploaded (0.00MB deduped)
wandb:                                                                                
wandb: Find user logs for this run at: /home/kpark53/code/NSR/run/True/2023-05-25/14-11-28/wandb/run-20230525_141128-3s2wkb14/logs/debug.log
wandb: Find internal logs for this run at: /home/kpark53/code/NSR/run/True/2023-05-25/14-11-28/wandb/run-20230525_141128-3s2wkb14/logs/debug-internal.log
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: 
wandb: Synced sparkling-firebrand-3: https://wandb.ai/nsr/ICML/runs/3s2wkb14
```

**Comment by kpark53** [comment]
Just FYI- These are the command prompts that I used.

```
export NUM=10K
make data/raw_datasets/10K
python3 scripts/data_creation/dataset_creation.py --number_of_equations 10000
python3 scripts/data_creation/filter_from_already_existing.py --data_path data/raw_datasets/10000 --csv_path test_set/nc.csv
python3 scripts/data_creation/apply_filtering.py --data_path data/raw_datasets/10000
python3 scripts/train.py
```

These are the outputs that I got.

```
There are 208 equations per block. The progress bar will have this resolution
Expression generation took 33.72859573364258 seconds
There are 208 equations per block. The progress bar will have this resolution
Expression generation took 108.76057147979736 seconds
Loading metadata
Creating image for validation set
Starting finding out index of equations present in the validation set or wih numerical problems
Total number of good equations 9988
Diving sets
[2023-05-25 14:11:28,103][lightning][INFO] - Global seed set to 9

[2023-05-25 14:11:29,810][lightning][INFO] - GPU available: True, used: True
[2023-05-25 14:11:29,811][lightning][INFO] - TPU available: None, using: 0 TPU cores
[2023-05-25 14:11:29,811][lightning][INFO] - Multi-processing is handled by Slurm.
[2023-05-25 14:11:29,811][lightning][INFO] - Using native 16bit precision.
```

**Comment by TommasoBendinelli** [comment]
Hi kpark53, I think you need to either generate a proper validation set (same procedure as the training one) or get rid of the default validation path. 
Best,
