### ISSUE TITLE
dataload_format_to_csv.py error ?

### ISSUE THREAD

**Issue by samholt** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#8]
Running : python scripts/csv_handling/dataload_format_to_csv.py raw_test_path=data/raw_datasets/200

Errors with 

`(nsrts) sam@lm-adastra:~/code/discovery/NeuralSymbolicRegressionThatScales$ python scripts/csv_handling/dataload_format_to_csv.py raw_test_path=data/raw_datasets/200
/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/core/plugins.py:202: UserWarning: 
        Error importing 'hydra._internal.core_plugins.importlib_resources_config_source'.
        Plugin is incompatible with this Hydra version or buggy.
        Recommended to uninstall or upgrade plugin.
                ModuleNotFoundError : No module named 'importlib_resources'
  warnings.warn(
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/_internal/utils.py", line 207, in run_and_report
    return func()
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/_internal/utils.py", line 329, in <lambda>
    lambda: Hydra.create_main_hydra2(
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 73, in create_main_hydra2
    config_loader: ConfigLoader = ConfigLoaderImpl(
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 78, in __init__
    self.repository: ConfigRepository = ConfigRepository(
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/_internal/config_repository.py", line 22, in __init__
    source_type = SourcesRegistry.instance().resolve(scheme)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/hydra/_internal/sources_registry.py", line 29, in resolve
    raise ValueError(
ValueError: No config source registered for schema pkg, supported types : [file, structured]`

Python: 3.9.7
hydra-core==1.0.0
hydralit==1.0.12
hydralit-components==1.0.9

OS: Ubuntu 20.04.4 LTS (Focal Fossa) (https://releases.ubuntu.com/20.04/)

Previously created the test 200 equation dataset in ./data/raw_datasets/200

Could you help point me in the right direction to run your repo ? Thank you so much ! 

Best,
Sam

**Comment by samholt** [comment]
Closing, fixed it by uninstalling `importlib_resources` and reinstalling `importlib_resources` to the latest version,

Thank you again
