### ISSUE TITLE
filter_from_already_existing.py Errors; 'asin' is not supported ?

### ISSUE THREAD

**Issue by samholt** [SymposiumOrganization/NeuralSymbolicRegressionThatScales#9]
Great project, just trying to replicate your results and training, however running your instructions I get;

```
python scripts/data_creation/filter_from_already_existing.py --data_path data/raw_datasets/100000 --csv_path test_set/test_nc.csv
Loading metadata
Creating image for validation set
Traceback (most recent call last):
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 130, in <module>
    main()
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 112, in main
    target_image = evaluate_validation_set(validation,support)
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 28, in evaluate_validation_set
    curr = lambdify(variables,row["eq"])(*support).numpy().astype('float16')
  File "<lambdifygenerated-16>", line 2, in _lambdifygenerated
NameError: name 'asin' is not defined
```

OS: Ubuntu 20.04.4 LTS (Focal Fossa)
Python: Python 3.9.7 

Packages - from a clean venv, installed the same ones with the repo, and had to update one or two to make the previous scripts work - see previous closed issue;

```
absl-py==1.0.0
aiohttp==3.8.1
aiosignal==1.2.0
altair==4.2.0
antlr4-python3-runtime==4.8
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
astor==0.8.1
asttokens==2.0.5
async-timeout==4.0.2
attrs==21.4.0
backcall==0.2.0
base58==2.1.1
beautifulsoup4==4.10.0
bleach==4.1.0
blinker==1.4
bokeh==2.4.2
brotlipy==0.7.0
bs4==0.0.1
cachetools==5.0.0
certifi==2021.10.8
cffi @ file:///opt/conda/conda-bld/cffi_1642701102775/work
charset-normalizer==2.0.12
click==8.0.4
compress-pickle==2.1.0
cryptography @ file:///tmp/build/80754af9/cryptography_1639414572950/work
dataclass-dict-convert==1.6.3
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
docker-pycreds==0.4.0
entrypoints==0.4
executing==0.8.3
frozenlist==1.3.0
fsspec==2022.2.0
future==0.18.2
gitdb==4.0.9
GitPython==3.1.27
google-auth==2.6.2
google-auth-oauthlib==0.4.6
grpcio==1.44.0
h5py==3.6.0
hydra-core==1.0.0
hydralit==1.0.12
hydralit-components==1.0.9
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
importlib-metadata==4.11.3
importlib-resources==5.4.0
ipykernel==6.9.2
ipython==8.1.1
ipython-genutils==0.2.0
ipywidgets==7.7.0
jedi==0.18.1
Jinja2==3.0.3
jsons==1.6.1
jsonschema==4.4.0
jupyter-client==7.1.2
jupyter-core==4.9.2
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.1.0
lxml==4.8.0
Markdown==3.3.6
MarkupSafe==2.1.1
matplotlib-inline==0.1.3
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186066731/work
mkl-service==2.4.0
mpmath==1.2.1
multidict==6.0.2
nbclient==0.5.13
nbconvert==6.4.4
nbformat==5.2.0
nest-asyncio==1.5.4
-e git+ssh://git@github.com/SymposiumOrganization/NeuralSymbolicRegressionThatScales.git@92d7c46c0417aeb76ecebcac982b8ccf1a3f8860#egg=nesymres&subdirectory=src
notebook==6.4.10
numexpr==2.8.1
numpy==1.22.3
oauthlib==3.2.0
omegaconf==2.1.1
ordered-set==4.1.0
packaging==21.3
pandas==1.4.1
pandocfilters==1.5.0
parso==0.8.3
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
prometheus-client==0.13.1
promise==2.3
prompt-toolkit==3.0.28
protobuf==3.19.4
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==7.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pydeck==0.7.1
pyDeprecate==0.3.1
Pygments==2.11.2
Pympler==1.0.1
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pyparsing==3.0.7
pyrsistent==0.18.1
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
python-dateutil==2.8.2
pytorch-lightning==1.5.10
pytz==2021.3
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
pyzmq==22.3.0
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
requests-oauthlib==1.3.1
rsa==4.8
scipy==1.8.0
semver==2.13.0
Send2Trash==1.8.0
sentry-sdk==1.5.8
setproctitle==1.2.2
shortuuid==1.0.8
six @ file:///tmp/build/80754af9/six_1644875935023/work
smmap==5.0.0
soupsieve==2.3.1
stack-data==0.2.0
streamlit==1.7.0
stringcase==1.2.0
sympy==1.10
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
termcolor==1.1.0
terminado==0.13.3
testpath==0.6.0
toml==0.10.2
toolz==0.11.2
torch==1.11.0
torchaudio==0.11.0
torchmetrics==0.7.2
torchvision==0.12.0
tornado==6.1
tqdm==4.63.0
traitlets==5.1.1
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
typish==1.9.3
tzdata==2022.1
tzlocal==4.1
urllib3==1.26.9
validators==0.18.2
wandb==0.12.11
watchdog==2.1.6
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.3
widgetsnbextension==3.6.0
yarl==1.7.2
yaspin==2.1.0
zipp==3.7.0
```

Any help to point to the right direction is greatly appreciated, thank you so much,

Best,
Sam

**Comment by TommasoBendinelli** [comment]
Hi Sam, thank you for getting in touch. 

Unfortunately, I have archived the project on my workstation and cannot replicate your setting. 
Python dependency is hell, and an update of a module has likely broken the function definition of "asin" (i.e., arcsine) in the script where you get the error. This code line: ` lambdify(variables,row["eq"])` works much like "eval". 
It needs all identifiers in the entry row["eq"] to be resolved somewhere. Otherwise, it fails.

In your case row["eq"]  returns a code object that needs to resolve the function definition of "asin", which is apparently nowhere to be found in the script

You can try to see if it works by doing "from math import asin" or "from numpy import arcsin as asin" on the top of the script.
I hope this helps. Otherwise, let me know.
Cheers,
Tommaso

**Comment by samholt** [comment]
Hi Tommaso,

Love the project, will try this now, thank you for the response,

A quick question, as this error is caused by dependencies is it possible for you to export your virtual environment package versions ? I.e. with something like `pip freeze > requirements.txt` or the equivalent for Conda. And paste them here, or upload them to the repo ?

Thank you so much,

Best,
Sam

**Comment by samholt** [comment]
Hi Tommaso,

I tried your suggestions, however neither of them worked. I tried the following `curr = lambdify(variables, row["eq"], modules=[{'asin': np.arcsin}, 'numpy'])(*support).numpy().astype('float16')` and it seems to run without halting, however still prints out errors that seem to be passed over. The errors are, and lots of them:

```
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'asin' is not defined
name 'asin' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'asin' is not defined
name 'asin' is not defined
name 'asin' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'Abs' is not defined
name 'asin' is not defined
name 'ln' is not defined
name 'ln' is not defined
name 'ln' is not defined
```

With a final halting error of 

```
Traceback (most recent call last):
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 141, in <module>
    main()
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 136, in main
    print(f"Total number of good equations {len([x for x in p if x[1]])}")
TypeError: 'Pool' object is not iterable
```

It is probably easiest if you could provide your list of packages in your virtual environment you used when you ran and developed your code, if you still have access to it. Otherwise if you can point me to where the `name 'ln' is not defined` error is coming from, I'll see if I can fix it and submit a PR to fix it for everyone else.

Thank you so much,

Best,
Sam

**Comment by TommasoBendinelli** [comment]
I have archived the project on my pc, and I don't have the exact environment anymore. I must admit I made the blunder at the time of placing the requirements.txt in the .gitignore file :(. However, I asked a colleague of mine who also installed the library to give him its environment. I hope it works. He uses the same virtual end for multiple projects; some might have changed a little or have redundant packages. 

But before trying to match the requirements, could you try to do "from sympy import *"?  According to sympy documentation asin and ln should be defined there. Does it work from your terminal if you do from sympy import asin?

Cheers,
```
absl-py                0.11.0
adapter-transformers   2.0.0
aiohttp                3.7.4.post0
antlr4-python3-runtime 4.8
argon2-cffi            20.1.0
astunparse             1.6.3
async-generator        1.10
async-timeout          3.0.1
attrs                  20.3.0
backcall               0.2.0
bleach                 3.2.1
blessings              1.7
cachetools             4.2.1
certifi                2020.12.5
cffi                   1.14.4
chardet                4.0.0
click                  7.1.2
configparser           5.0.2
contrib                0.3.0
cycler                 0.10.0
Cython                 0.29.22
dataclass-dict-convert 1.4.2
datasets               1.6.0
decorator              4.4.2
defusedxml             0.6.0
dill                   0.3.3
docker-pycreds         0.4.0
entrypoints            0.3
fancycompleter         0.9.1
fenics                 2018.1.0
fenics-dijitso         2018.1.0
fenics-ffc             2018.1.0
fenics-fiat            2018.1.0
fenics-ufl             2018.1.0
filelock               3.0.12
flatbuffers            1.12
fsspec                 0.8.7
future                 0.18.2
gast                   0.3.3
gitdb                  4.0.5
GitPython              3.1.14
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
gplearn                0.4.1
gpustat                0.6.0
gpustats               0.0.1
graphviz               0.16
grpcio                 1.32.0
h5py                   2.10.0
huggingface-hub        0.0.8
hydra-core             1.0.5
hydra-joblib-launcher  1.1.1
idna                   2.10
importlib-resources    5.1.0
iniconfig              1.1.1
install                1.3.4
ipykernel              5.4.2
ipython                7.19.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
jitcdde                1.4.0
jitcxde-common         1.4.1
jiwer                  2.2.0
joblib                 1.0.0
jsons                  1.4.0
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.7.0
jupyterlab-pygments    0.1.2
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
llvmlite               0.36.0
Markdown               3.3.3
MarkupSafe             1.1.1
matplotlib             3.3.4
mistune                0.8.4
mpmath                 1.1.0
multidict              5.1.0
multiprocess           0.70.11.1
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.3
notebook               6.1.5
nptyping               1.4.0
numba                  0.53.0
numexpr                2.7.2
numpy                  1.19.5
nvidia-ml-py3          7.352.0
oauthlib               3.1.0
omegaconf              2.0.6
opt-einsum             3.3.0
ordered-set            4.0.2
packaging              20.8
pandas                 1.2.1
pandocfilters          1.4.3
parso                  0.7.1
pathtools              0.1.2
pdbpp                  0.10.2
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 8.1.0
Pint                   0.16.1
pip                    20.3.1
pluggy                 0.13.1
prometheus-client      0.9.0
promise                2.3
prompt-toolkit         3.0.8
protobuf               3.14.0
psutil                 5.8.0
ptyprocess             0.6.0
py                     1.10.0
pyarrow                3.0.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.3
pyparsing              2.4.7
pyrepl                 0.9.0
pyrsistent             0.17.3
pytest                 6.2.2
python-dateutil        2.8.1
python-Levenshtein     0.12.2
pytorch-lightning      1.2.4
pytz                   2020.5
PyYAML                 5.3.1
pyzmq                  20.0.0
qtconsole              5.0.1
QtPy                   1.9.0
regex                  2021.3.17
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.7
sacremoses             0.0.43
scikit-learn           0.24.1
scipy                  1.6.0
seaborn                0.11.1
Send2Trash             1.5.0
sentry-sdk             1.0.0
setuptools             51.0.0
shortuuid              1.0.1
six                    1.15.0
sklearn                0.0
smmap                  3.0.5
SoundFile              0.10.3.post1
stringcase             1.2.0
subprocess32           3.5.4
symengine              0.7.2
sympy                  1.7.1
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
tensorflow-estimator   2.4.0
termcolor              1.1.0
terminado              0.9.1
testpath               0.4.4
threadpoolctl          2.1.0
timesynth              0.2.4
tokenizers             0.10.1
toml                   0.10.2
torch                  1.7.1
tornado                6.1
tqdm                   4.49.0
traitlets              5.0.5
transformers           4.4.2
typing-extensions      3.7.4.3
typish                 1.9.1
urllib3                1.26.3
wandb                  0.10.22
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.36.1
widgetsnbextension     3.5.1
wmctrl                 0.3
wrapt                  1.12.1
xxhash                 2.0.2
yarl                   1.6.3
```

**Comment by samholt** [comment]
Thank you for the requirements.

I tried "from sympy import *", in the script however I still got the same error above, that of `NameError: name 'asin' is not defined`.

When I matched the requirements and re-ran all the steps again they were able to complete, however I did still get the same error of 

```
Traceback (most recent call last):
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 141, in <module>
    main()
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 136, in main
    print(f"Total number of good equations {len([x for x in p if x[1]])}")
TypeError: 'Pool' object is not iterable
```

However it seems this is just a print line statement so just commented the line out, and it seemed to produce a dataset in `data/datasets/100000`.

Is this correct, it seemed to only produce two files, in `data/datasets/100000`, that of `0.h5` and `metadata.h5`. Or should I be expecting many files, as in `data/raw_datasets/100000` is see many `.h5` files i.e. `0.h5` through to `24.h5`.

I would greatly appreciate your comment on if this is correct or not. Thank you so much again, and love this project.

Best,
Sam

**Comment by TommasoBendinelli** [comment]
Hi Sam, that's not correct. Ideally, that script filters out functions in the test set or that are all nans/+inf/-inf. But it seems like all functions are filtered out in your case.
I have really no idea what is not working for you. Before releasing the code, I tested the entire pipeline, and everything was running smoothly. Could you try the following?
Can you set the argument "csv_path" to None and the option to debug to True? Then, make a print statement at line 72 of the variable "curr" and print some output here?

**Comment by samholt** [comment]
Hi Tommaso,

Interesting, thank you for responding. 

Sure the output from doing that is:

```
[inf, 0.3918, inf, 0.4678, inf, 0.755, 151.8, 752.5, inf, 0.06573, -0.9756, 0.6406, 0.09985, 0.7036, 117.8, -0.8477, 2.613, -0.4644, 1.18, -0.755, -0.2314, inf, -0.3032, -0.999, 1.03, 70.25, inf, inf, 1.022, 9.484, inf, -0.2698, 97.1, inf, 0.9224, inf, inf, -0.9697, -0.999, 406.0, inf, 38050.0, 0.8306, 49.94, -0.9727, -0.966, inf, 1.137, -0.4077, inf, 0.2634, 213.4, inf, 50.03, inf, 0.5107, 0.8145, inf, 1.297, 0.7524, 0.9116, inf, 0.6133, inf, inf, 227.6, 0.9053, 0.899, 0.9556, 2.434, inf, -0.696, 0.6577, 0.59, -0.619, 7028.0, 21.31, 0.75, 0.5693, 0.2218, inf, 41.44, 23.6, 1.594, 0.9307, inf, 0.9424, 7.867, inf, inf, 0.9546, 0.538, -0.6846, inf, -0.934, 0.00889, -0.08997, 6336.0, inf, -0.907, inf, 0.02763, inf, 0.9854, 0.7446, -0.54, inf, inf, 1.064, 92.44, -0.9897, 34340.0, inf, inf, inf, inf, 1.151, 0.6147, inf, 0.9883, inf, inf, -0.08167, -0.987, 2002.0, -1.0, 106.6, inf, 1.234, -0.9126, 0.955, -0.789, 0.962, 0.9365, 0.6426, 0.2422, 0.006214, -0.998, 0.751, -0.9023, inf, inf, 1.235, 0.946, -0.1528, -0.619, inf, -0.2163, 0.8784, 21.98, -0.9287, 96.94, 0.6606, 0.3457, 1.212, 0.981, 0.632, 0.7446, 86.8, 124.0, 1.007, 0.671, 1.0205, 3.553, -0.5303, inf, 12.805, 439.2, inf, 0.4702, inf, -0.9644, inf, -0.769, inf, inf, inf, 460.5, inf, 0.7197, -0.3706, inf, 3.525, -0.9556, inf, 1.221, -0.733, inf, 0.05115, inf, 217.8, 928.0, inf, inf, inf, inf, -0.826, 0.998, inf, 21490.0, 1.161, 218.6, 1.064, 0.9336, -0.686, inf, -0.5044, inf, 0.871, inf, -0.0776, -0.4138, inf, -0.3196, inf, -0.6143, -0.951, 1.068, 0.982, 26530.0, inf, inf, -0.1702, 1.181, 1.221, 1.962, 16930.0, 3464.0, -0.322, -0.335, inf, -0.584, -0.6562, inf, 116.4, -0.9907, 0.5015, -0.0517, 24380.0, 12344.0, 864.0, -0.5444, 1.164, -0.2062, -0.9795, 0.9272, -0.2495, -0.2825, inf, inf, inf, 0.8813, inf, 66.5, 1502.0, inf, 0.02507, -0.925, 0.505, inf, inf, -0.09326, -0.5825, inf, 0.954, 9610.0, inf, inf, 26380.0, 0.981, inf, 0.2236, 0.997, inf, inf, inf, 0.672, -0.8066, inf, inf, -0.9062, 0.899, 27730.0, inf, 2386.0, inf, 2632.0, 516.5, 16.78, inf, inf, 0.1534, 0.5073, -0.4614, inf, inf, 1.0, inf, 8376.0, -0.893, inf, -0.619, 49.72, 0.998, -0.5547, 3.947, -0.6504, -0.258, 3.758, 420.5, inf, -0.9575, 35840.0, 1.405, inf, 1.026, -0.3965, inf, inf, 0.633, 2.742, -0.8843, inf, -0.446, inf, 1.114, inf, inf, inf, inf, inf, 14.35, -0.271, -0.8726, 0.772, 6.29, 333.8, 1086.0, 0.586, 96.2, -0.1849, -1.0, 0.853, inf, inf, 1581.0, -0.4644, 0.9653, 1.232, inf, 1.151, inf, -0.2788, -0.05515, 0.997, 0.2502, inf, inf, inf, 0.1414, 0.752, 166.8, 1.216, 0.8647, -0.891, inf, inf, 0.997, inf, inf, 1.006, 0.714, 1.077, 7064.0, 0.4446, -0.773, 0.2424, 30.81, inf, 1.104, -0.989, 0.2922, inf, 1.091, 0.812, -0.47, -0.865, -0.8906, -0.882, 0.03772, inf, inf, 11650.0, 0.365, 5.19, inf, inf, 29970.0, 0.3137, 35600.0]
  6%|███████████████                              
```

Let me know if I can re-create any further diagnostic information for you. 

Thank you so much,

Best,
Sam

**Comment by TommasoBendinelli** [comment]
Is giving you 6% only for one equation? How big is your dataset?

**Comment by samholt** [comment]
No that was after a while, the dataset is 100K equations large, there was many similar printing outputs before I stopped it and copied that console output.

**Comment by TommasoBendinelli** [comment]
Ah okey! Just try to run in that configuration and check whether it works. The last print (i.e. the one that was failing) tells you how many equations you have available for the training.

**Comment by samholt** [comment]
It runs, and produces two files, in `data/datasets/100000`, that of `0.h5` and `metadata.h5`. I think it has worked, as `0.h5` has a size of about 138M.

If you think there is anything else I can do, do let me know.

I also noticed in the makefile, a few scripts are missing in the repo, i.e. `filter_validation.py` and `to_h5.py`. Are these needed ? 

Thank you so much,

Best,
Sam

**Comment by TommasoBendinelli** [comment]
Hi Sam, 
I am glad it worked. For some reason, it appears that all the equations you produced are in the test set. This is weird, might an issue in the random seed during dataset generation (all workers have the same random seed?), I don't really know there. If you want to investigate further would be nice to know the following:
* What you get out of this ? (f"Total number of good equations {len([x for x in p if x[1]])}") 
* Does it work also when debug flag is false?
* Do you get any printing when you set back the --csv_path or all equations goes are ignored due to the if/else at line 60?

Otherwise if you want to play a bit with the training code, I think you are good to go. 
The only difference when you are passing --csv_path None is that you are not filtering out these equations, so they might be present in the training set (of course the numerical constants are randomized so still for each equation that are infinite different combinations).

Best,

**Comment by samholt** [comment]
Interesting, ah that is troublesome. I would like fully re-create your work here to compare it as a baseline in a work in progress paper, in a different similar problem.

Thank you so much for the quick replies,

Could you try installing the packages and seeing if you can run everything end to end ? And then if that works, or anything you found that you ran into, and or solved post it here.

I think all workers appear to have different random seeds, as they generate different blocks of equations when saved out.

(f"Total number of good equations {len([x for x in p if x[1]])}") fails with the above error, also here:

```
Traceback (most recent call last):
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 141, in <module>
    main()
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sam/anaconda3/envs/nsrts/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sam/code/discovery/NeuralSymbolicRegressionThatScales/scripts/data_creation/filter_from_already_existing.py", line 136, in main
    print(f"Total number of good equations {len([x for x in p if x[1]])}")
TypeError: 'Pool' object is not iterable
```

1. It seems maybe the multiprocessing package, that your colleague posted could be too recent for the code.
2. Yes it does
3. Yes I do get printing still

Do let me know what you think of the above, and if you are able to replicate the steps on your machine.

Thank you so much for your time,

I greatly look forward to hearing from you,

Best,
Sam

**Comment by TommasoBendinelli** [comment]
Ahh I am happy that you want to include it your baseline comparison! 
I have a looked a bit at the git history, and might be a simple typo in the very last commit.  
Could you run again the code, with the correct validation set and not debug but changing line 126 from:

`print(f"Total number of good equations {len([x for x in p if x[1]])}")`

to:

`print(f"Total number of good equations {len([x for x in res if x[1]])}")`

And let me know what it prints

**Comment by samholt** [comment]
Great doing that and running it again I see

```
python scripts/data_creation/filter_from_already_existing.py --data_path data/raw_datasets/100000 --csv_path test_set/test_nc.csv
Loading metadata
Creating image for validation set
Starting finding out index of equations present in the validation set or wih numerical problems
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100000/100000 [00:42<00:00, 2373.95it/s]
Pool  <multiprocessing.pool.Pool state=TERMINATE pool_size=24>
Pool  <class 'multiprocessing.pool.Pool'>
Total number of good equations 94527
```

I presume this mean that it is working ?

Best,
Sam

**Comment by TommasoBendinelli** [comment]
Hi Sam, 

Yeah it is working. Turns out was just that typo (and the requirements). 

Best,

**Comment by samholt** [comment]
Thank you for the quick response, and confirmation of that,

Best,
Sam
